openapi: '3.0.2'
info:
  title: Tidal Desktop Unofficial Documentation
  version: '0.1a'
  description: "Unofficial documentation for the `desktop.tidal.com` url for tidal.
    Can be used in order to navigate and browse around tidal."
servers:
  - url: https://desktop.tidal.com/v1
paths:
  /rt/connect:
    summary: Unknown, serves a websocket url that is currently unused?
    post:
      parameters:
        -
          $ref: "#/components/parameters/countryCode"
        -
          $ref: "#/components/parameters/locale"
        -
          $ref: "#/components/parameters/deviceType"
      responses:
        '200':
          description: Ok response, with websocket url
          content: 
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string

  /country/context:
    summary: Returns the users country code?
    get:
      security:
        - ApiKeyAuth: []
      parameters:
        -
          $ref: "#/components/parameters/countryCode"
        -
          $ref: "#/components/parameters/locale"
        -
          $ref: "#/components/parameters/deviceType"
      responses:
        '200':
          description: user's country code
          content:
            application/json:
              schema:
                type: object
                properties:
                  countryCode:
                      type: string
  /pages/home:
    summary: Get home page information.
    get:
      parameters:
        -
          $ref: "#/components/parameters/countryCode"
        -
          $ref: "#/components/parameters/locale"
        -
          $ref: "#/components/parameters/deviceType"
      responses:
        '200':
          $ref: "#/components/responses/pages"

  /ping:
    summary: Sends back a 200 OK response.
    get:
      security: []
      responses:
        '200':
          description: Ok
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-tidal-token
  schemas:
    # Need to remove once I have actual moduel types inserted.
    cool_temporary: 
      type: object
    cool_temporary2: 
      type: object
    baseModule: 
      type: object 
      allOf:
        - $ref: "#/components/schemas/baseObject"
        - properties:
            description:
              type: string
              description: description of the object I guess? Seems to always be empty to me.
            preTitle: 
              type: string 
              description: Always seems to be null. Don't know yet.
            showMore: 
              type: string
              description: Always null so far, not sure what this is.
            width:
              type: integer 
              description:  Always seems to be 100.
    baseObject:
      type: object
      required: 
        - id 
        - title
      properties:
        id:
          type: string 
          description: base64 encoded json object with identification information? pV and v properties, idk.
        title:
          type: string 
          description: Title of whatever you're looking at.
    modules:
      type: array
      items:
        type: object
        allOf: 
          - $ref: "#/components/schemas/baseModule"
          - oneOf:
            - $ref: "#/components/schemas/cool_temporary"
            - $ref: "#/components/schemas/cool_temporary2"
            discriminator:
              propertyName: type
              mapping: 
                tmp: "#/components/schemas/tmp"
                tmp2: "#/components/schemas/tmp2"

  responses: 
    pages:
      description: A page returned by the tidal desktop api.
      content:
        application/json:
          schema:
            type: object
            required:
              - rows 
              - selfLink
            allOf: 
            - type: object
              properties:
                rows:
                  type: array
                  items:
                    type: object
                    properties:
                      modules:
                        $ref: "#/components/schemas/modules"
                selfLink:
                  type: object
                  description: "As of yet unknown, always null?"
                  properties: {}
            - $ref: "#/components/schemas/baseObject"

  parameters:
      countryCode:
          name: countryCode
          in: query
          description: user's country code. This parameter is wierd, locally it always sends "WW"
            however the country endpoint respounds something different, US for me. Changing it dosen't seem to do anything.
          schema:
            type: string
      locale:
          name: locale
          in: query 
          description: The user's locale, e.g. en_US. I'm not as of yet sure what
            all the available locales are.
          schema:
            type: string
      deviceType:
          name: deviceType
          in: query 
          description: user's device type, only DESKTOP is known currently.
          schema:
            type: string
            enum: [DESKTOP]
      x-tidal-token:
        name: x-tidal-token
        in: header
        description: The user's tidal token
        schema:
          type: string